version: '3'
services:
  api:
    build: . 
    depends_on:
      - postgres
    ports:
      - 8000:8000
    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=8a94cefd021ba3a82e8373edc4983d365a9863a5f5db3bed1d5bf1de8c1845c7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data/

volumes:
  postgres-db: 